# Theme Details

name = "Thyme Theme"
license = "GNU GPL V3"
licenselink = "https://github.com/FrappeFortyTwo/Thyme/blob/main/LICENSE"
homepage = "https://souravsingh.dev/"
tags = ["Blog","Responsive","Clean","Simple","Minimal","Personal","Fast","Light",]
features = ["Simple clean design","Light and mobile friendly","Zero initial configuration"]
min_version = "0.41.0"

# Site Parameters

sectionPagesMenu = "main"
title = "Sourav Singh"


# Author Details

[author]
  name = "Sourav Singh"
  homepage = "https://souravsingh.dev"

# Site Parameters

[params]
  title = "Sourav Singh"
  description = "A minimal personal website theme that supports blogs, mermaid js and katex."
  license = "MIT"

# Markup Hightlight

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = "true"
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "rrt"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
